-- 用户信息表
-- DROP TABLE IF EXISTS T_USER;
CREATE TABLE IF NOT EXISTS T_USER (
  ID            VARCHAR(32),
  MOBILE        VARCHAR(20),
  EMAIL         VARCHAR(99),
  USERNAME      VARCHAR(20),
  PASSWORD      VARCHAR(32),
  STATUS        TINYINT NOT NULL,
  NICKNAME      TEXT,
  HEAD_IMG_URL  TEXT,
  SEX           TINYINT,
  COUNTRY       TEXT,
  PROVINCE      TEXT,
  CITY          TEXT,
  CREATION_TIME BIGINT  NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (MOBILE),
  UNIQUE (EMAIL),
  UNIQUE (USERNAME)
);

